### PR TITLE
#19 - Fix issue with I18N

### PR DESCRIPTION
**Pull request by coelle**
Java tries to load the properties with the "language extension" which
matches the current system: "If still no result bundle is found, the base
name alone is looked up."
See https://docs.oracle.com/javase/7/docs/api/java/util/ResourceBundle.html

### CODE REVIEW

**Comment by jchambers** [comment]
First and foremost, thank you for the contribution! While we only have one language, does it make more sense to rename the existing English-specific `.properties` file to be non-locale-specific rather than introducing a new copy?

**Comment by coelle** [comment]
As long as there is only one language, having only the base .properties file is ok. But for issue #14 you should maintain the copied file...

**Comment by jchambers** [comment]
Makes sense. How about a symlink, though?

**Comment by coelle** [comment]
Seems legit. I tried it by solving #14 for german (see pull request #21)  ;-)

**Comment by coelle** [comment]
May be you should drop this pull request and accept #21 instead.

**Comment by coelle** [comment]
The symlink solution might raise issues. I opened pull request #22 with an updated solution.

**Pull request closed without merging**
